### ISSUE TITLE
dataset not found

### ISSUE THREAD

**Issue by bhaavansai** [facebookresearch/TaskGraph#3]
line 30, in __init__
    with open(COIN_ANNOTATIONS_PATH) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/datasets01/COIN/053122/COIN.json'

i'm not able to find this folder anywhere datasets01, i have downloaded and extracted all the mentioned zip files.
![image](https://github.com/facebookresearch/TaskGraph/assets/133352380/14902c0e-7e2c-44fa-bf96-83de38d69310)

can anybody please help

**Comment by thechargedneutron** [comment]
This is the COIN annotation file provided in the dataset. See COIN.json here: https://github.com/coin-dataset/annotations

**Comment by thechargedneutron** [comment]
Closing this issue, feel free to re-open if you are still having issues with accessing COIN annotations.
