### ISSUE TITLE
Question about Populating task graph

### ISSUE THREAD

**Issue by Flaick** [facebookresearch/TaskGraph#4]
Hello, thank you for the impressive work, though I have a question about the task graph construction. 

It looks like the graph is built upon textual labels of evaluation videos (COIN/CrossTask), as shown in the line 279-295 in zero-shot/video.py. Isn't this a data leakage for the following graph-based keystep correction?

Thanks,

Kun.

**Comment by thechargedneutron** [comment]
The knowledge of the keystep set is assumed to be known. For example, COIN has 749 keysteps and CrossTask has 105 keysteps. Note that we do not assume the temporal location of the keystep -- just the keysteps names. The task is to predict the location of the keystep. This is typical for all the baselines used in the paper and all action recognition work in general.

**Comment by Flaick** [comment]
Thanks for the response, sorry that I make the question unclear. My question actually refers to the line #205 in text.py, where you call **task_graph.register_sequence** to populate the scores from **eval_dataset**. During the **task_graph.register_sequence**, the following codes are run and I think it updates the task_graph with the frame-wise transition frequency. Is this correct? Thanks!
```python
  for time_idx in range(len(best_keysteps)):
      source = dest
      # if sim[time_idx, best_keysteps[time_idx]] > 0.5:
      dest = keystep_sents[int(best_keysteps[time_idx])]
      # else:
      #     continue
      if source is None:
          continue
      if source not in self.task_graph[input_modality]:
          self.task_graph[input_modality][source] = {dest: 1}
      if dest not in self.task_graph[input_modality][source]:
          self.task_graph[input_modality][source][dest] = 1
      else:
          self.task_graph[input_modality][source][dest] += 1
```

**Comment by thechargedneutron** [comment]
Thanks! This is the `predicted` assignment and not the `ground-truth` keystep assignment. Our algorithm works as follows - 

1. Use sentence similarity to find the 'predicted' assignment
2. Use task graph to 'correct' the predictions by refining using task graph.

Is this clear now?

**Comment by Flaick** [comment]
Ah yes! I just find that it pass the sim score, not the gt label. Thanks!
